export enum NavigationEnum {
  EmployeeList = '/employees',
  EmployeeCreate = '/employees/create',
  EmployeeView = '/employees/[id]',
  StoreList = '/stores',
  StoreCreate = '/stores/create',
  StoreView = '/stores/[id]',
  ProductList = '/products',
  ProductCreate = '/products/create',
  ProductView = '/products/[id]',
  Report = '/report',
  SalesReport = '/report/sales-report',
  ProductReport = '/report/product-report',
  Login = '/login',
  Home = '/',
  Profile = '/profile',
  ProfileChangePassword = '/profile/change-password',
  WholesaleOrderList = '/wholesale-orders',
  WholesaleOrderView = '/wholesale-orders/[id]',
}
