export const PERMISSIONS = {
  AccessStaffTab: 'employee.employees.page',
  AccessStaffList: 'employee.employees.list',
  AccessStaffDetail: 'employee.employees.view',
  AddNewStaff: 'employee.employees.create',
  UpdateStaff: 'employee.employees.update',
  DeleteStaff: 'employee.employees.delete',
  ManageEmployee: 'employee.employees:manage',
  AccessStoreTab: 'employee.stores.page',
  AccessStoreList: 'employee.stores.list',
  AccessStoreDetail: 'employee.stores.view',
  AddNewStore: 'employee.stores.create',
  UpdateStore: 'employee.stores.update',
  DeleteStore: 'employee.stores.delete',
  ManageStore: 'employee.stores:manage',
  AccessProductTab: 'employee.products.page',
  AccessProductList: 'employee.products.list',
  AccessProductDetail: 'employee.products.view',
  AddNewProduct: 'employee.products.create',
  UpdateProduct: 'employee.products.update',
  DeleteProduct: 'employee.products.delete',
  ImportProductData: 'employee.products.import',
  ImportSalesProductData: 'employee.products.import-sales',
  ManageProduct: 'employee.products:manage',
  AccessReportTab: 'employee.reports.page',
  AccessSalesReport: 'employee.reports.sales',
  AccessProductReport: 'employee.reports.products',
  ManageReport: 'employee.reports:manage',
  ImportWholesaleOrderData: 'employee.wholesale-orders.import',
  AccessWholesaleOrderTab: 'employee.wholesale-orders.page',
  AccessWholesaleOrderList: 'employee.wholesale-orders.list',
  AccessWholesaleOrderDetail: 'employee.wholesale-orders.view',
  DeleteWholesaleOrder: 'employee.wholesale-orders.delete',
  UpdateWholesaleOrderToPaid: 'employee.wholesale-orders.paid',
  UpdateWholesaleOrderToUnpaid: 'employee.wholesale-orders.unpaid',
  GetWholesaleOrderInvoice: 'employee.wholesale-orders.invoice',
  ManageWholesaleOrder: 'employee.wholesale-orders:manage',
} as const;
export type PermissionValuesType =
  (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
